require("hakim.plugins")
require("hakim.settings")
require("hakim.keybinds")
require("hakim.colorscheme")
require("hakim.plugins.comment")
require("hakim.plugins.nvim-tree")
require("hakim.plugins.lualine")
require("hakim.plugins.autopairs")
require("hakim.plugins.gitsigns")
require("hakim.plugins.telescope")
require("hakim.plugins.treesitter")
require("hakim.plugins.lsp-zero")
require("hakim.plugins.blankline")
require("hakim.plugins.toggleterm")

